"""Generative null model — does a slot-grammar generator reproduce Voynichese?

Hypothesis (from Phase 2 morphology): Voynichese words are generated by
sampling each glyph position independently from a position-specific
distribution.

Test: fit such a model on real Voynichese and ask whether samples from it
reproduce the macroscopic statistics — graph density, h2 entropy, Zipf
slope, family-size distribution. If yes, the slot-grammar hypothesis is
strongly supported. If no, we identify which statistic the model misses
and learn what extra structure Voynichese has beyond independent slots.

Three null models, in increasing complexity:

  M1. Position×Length:
      For each word length L, fit P(g | pos, length) from all real words of
      length L. Sample synthetic words by drawing length L from the
      empirical length distribution, then drawing each position
      independently.

  M2. Position×Length + word-frequency-weighted:
      Same as M1 but the per-position distributions are weighted by word
      token counts (so a word appearing 100 times contributes 100x to the
      slot statistics).

  M3. Family-conditional position×length:
      Fit a separate slot model per family (top 30 from word_families.py),
      sample family proportional to family token mass, then sample inside
      family with its slot distribution. This is closer to "word
      generation by template choice + slot fill".

For each model we sample N synthetic word tokens (N = real token count,
36,634), tabulate them as a synthetic corpus, and compute the same
statistics that we computed on real Voynichese in earlier phases.

Outputs:
  generative_results.json
  generative_summary.csv
"""

from __future__ import annotations

import json
import math
import random
import sys
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent
DATA = ROOT.parent / "data"
sys.path.insert(0, str(ROOT))
from analyze import parse_eva, tokenise_glyphs  # noqa: E402
from word_families import build_ed1_graph, graph_stats, connected_components  # noqa: E402

random.seed(20260502)


def load_real():
    records = parse_eva(DATA / "voynich_eva.txt")
    records = [r for r in records if r["src"] == "H"]
    real_words = []  # token stream
    for r in records:
        for w in r["words"]:
            if not w or any(c in "*!" for c in w):
                continue
            real_words.append(w)
    return real_words


def fit_position_length_model(words: list[str], weighted: bool = True):
    """Returns:
        length_dist:          {L: count}
        slot_dist[L][pos]:    Counter of glyph -> count
    """
    length_dist: Counter = Counter()
    slot: dict[int, list[Counter]] = defaultdict(list)
    for w in words:
        toks = tokenise_glyphs(w)
        L = len(toks)
        if L < 2 or L > 12:
            continue
        weight = 1  # word counts are already in `words` since each token appears
        length_dist[L] += weight
        if not slot[L]:
            slot[L] = [Counter() for _ in range(L)]
        for pos, g in enumerate(toks):
            slot[L][pos][g] += weight
    return length_dist, slot


def sample_word(length_dist, slot, rng=random) -> str:
    Ls, ws = zip(*length_dist.items())
    L = rng.choices(Ls, weights=ws, k=1)[0]
    parts = []
    for pos in range(L):
        c = slot[L][pos]
        items, w = zip(*c.items())
        parts.append(rng.choices(items, weights=w, k=1)[0])
    return "".join(parts)


def fit_family_models(words: list[str], n_families: int = 30):
    """Group word tokens by their family in the Phase 2 graph.

    For each of the top families, fit a position×length model on ITS member
    words. Family weight = total token count of that family.
    """
    fam_path = ROOT / "voynich_families.json"
    fam = json.loads(fam_path.read_text(encoding="utf-8"))
    families = fam["families"][:n_families]

    # Map word -> family index, by looking at members_preview head + slot
    # summary modal length. We'll re-derive properly: build the graph,
    # connected components, then assign words.
    counts: Counter = Counter(w for w in words if w)
    types = [w for w, c in counts.items() if c >= 2]
    # filter same way as Phase 2
    type_filtered = []
    type_tokens: list[tuple[str, ...]] = []
    for w in types:
        toks = tuple(tokenise_glyphs(w))
        if len(toks) < 2 or len(toks) > 20:
            continue
        if any(t in {"*", "!"} for t in toks):
            continue
        type_filtered.append(w)
        type_tokens.append(toks)

    adj = build_ed1_graph(type_tokens)
    comps = connected_components(adj, len(type_filtered))
    word_to_fam: dict[str, int] = {}
    fam_token_total: dict[int, int] = {}
    fam_word_lists: dict[int, list[str]] = {}
    fam_index = 0
    for comp in comps:
        if len(comp) < 3:
            continue
        # repeat each word as many times as its token count, so slot stats
        # are token-frequency weighted
        ws_in_fam = []
        total = 0
        for i in comp:
            w = type_filtered[i]
            ws_in_fam.extend([w] * counts[w])
            total += counts[w]
        fam_word_lists[fam_index] = ws_in_fam
        fam_token_total[fam_index] = total
        for i in comp:
            word_to_fam[type_filtered[i]] = fam_index
        fam_index += 1

    # Train a model per family
    fam_models = {}
    for fi, ws in fam_word_lists.items():
        ld, sd = fit_position_length_model(ws)
        fam_models[fi] = (ld, sd, fam_token_total[fi])

    # Out-of-family bucket: rare/hapax + small components
    out_of_fam_words = [w for w in words
                        if w and w not in word_to_fam and not any(c in "*!" for c in w)]
    if out_of_fam_words:
        ld, sd = fit_position_length_model(out_of_fam_words)
        fam_models[-1] = (ld, sd, len(out_of_fam_words))

    return fam_models


def sample_corpus_from_M1_M2(words: list[str], n_samples: int) -> list[str]:
    ld, sd = fit_position_length_model(words)
    return [sample_word(ld, sd) for _ in range(n_samples)]


def sample_corpus_from_M3(words: list[str], n_samples: int) -> list[str]:
    fam = fit_family_models(words)
    fam_keys = list(fam.keys())
    fam_weights = [fam[k][2] for k in fam_keys]
    out = []
    for _ in range(n_samples):
        fi = random.choices(fam_keys, weights=fam_weights, k=1)[0]
        ld, sd, _ = fam[fi]
        out.append(sample_word(ld, sd))
    return out


# ------------------------- statistics on a corpus ---------------------------

def shannon_entropy(c: Counter) -> float:
    n = sum(c.values())
    return -sum((v / n) * math.log2(v / n) for v in c.values() if v > 0) if n else 0.0


def conditional_entropy(stream: list[str]) -> tuple[float, float]:
    """h1 (unigram) and h2 (conditional bigram) entropy in bits."""
    n = len(stream)
    if n < 3:
        return (0.0, 0.0)
    c1 = Counter(stream)
    h1 = shannon_entropy(c1)
    bg = Counter(zip(stream[:-1], stream[1:]))
    prev = Counter(stream[:-1])
    h2 = 0.0
    for (a, b), c in bg.items():
        pab = c / (n - 1)
        pa = prev[a] / (n - 1)
        if pab > 0 and pa > 0:
            h2 -= pab * math.log2(pab / pa)
    return (h1, h2)


def zipf_fit(c: Counter) -> tuple[float, float]:
    freqs = sorted(c.values(), reverse=True)
    if len(freqs) < 5:
        return (float("nan"), float("nan"))
    ranks = np.arange(1, len(freqs) + 1)
    x = np.log10(ranks)
    y = np.log10(np.array(freqs))
    A = np.vstack([x, np.ones_like(x)]).T
    slope, intercept = np.linalg.lstsq(A, y, rcond=None)[0]
    yhat = slope * x + intercept
    ss_res = float(np.sum((y - yhat) ** 2))
    ss_tot = float(np.sum((y - y.mean()) ** 2))
    return (float(slope), 1.0 - ss_res / ss_tot if ss_tot > 0 else float("nan"))


def repetition_rate(words: list[str]) -> float:
    """Fraction of consecutive identical-word adjacencies."""
    n = 0
    rep = 0
    for a, b in zip(words[:-1], words[1:]):
        n += 1
        if a == b:
            rep += 1
    return rep / n if n else 0.0


def corpus_summary(words: list[str], label: str) -> dict:
    word_counts = Counter(words)
    glyph_stream = []
    for w in words:
        glyph_stream.extend(tokenise_glyphs(w))
    h1, h2 = conditional_entropy(glyph_stream)
    z, r2 = zipf_fit(word_counts)
    types = [w for w, c in word_counts.items() if c >= 2]
    type_tokens = [tuple(tokenise_glyphs(w)) for w in types
                   if 2 <= len(tokenise_glyphs(w)) <= 20]
    type_kept = [w for w in types
                 if 2 <= len(tokenise_glyphs(w)) <= 20]
    adj = build_ed1_graph(type_tokens)
    gs = graph_stats(adj, len(type_kept), label)
    hapax = sum(1 for c in word_counts.values() if c == 1)
    n = sum(word_counts.values())
    avg_wlen = sum(len(tokenise_glyphs(w)) * c for w, c in word_counts.items()) / n if n else 0
    return {
        "label": label,
        "n_tokens": n,
        "n_types": len(word_counts),
        "hapax_ratio": hapax / len(word_counts) if word_counts else 0,
        "avg_word_length": avg_wlen,
        "h1_unigram": h1,
        "h2_conditional": h2,
        "zipf_slope": z,
        "zipf_r2": r2,
        "repetition_rate": repetition_rate(words),
        "graph_n_types_used": gs["n_types"],
        "graph_avg_degree": gs["avg_degree"],
        "graph_largest_share": gs["largest_component_share"],
        "graph_clustering": gs["avg_clustering_coef"],
        "graph_components_geq_10": gs["size_geq_10_components"],
    }


def main():
    print("Loading real Voynichese token stream...")
    real_words = load_real()
    n_tokens = len(real_words)
    print(f"  {n_tokens} tokens, {len(set(real_words))} types")

    print("\nReal corpus stats...")
    real = corpus_summary(real_words, "Real Voynichese")
    print(json.dumps(real, indent=2, ensure_ascii=False))

    print("\nM1 (position × length, type-level fit)...")
    type_only = list(set(real_words))  # de-duplicated for M1 (no token weighting)
    m1_words = sample_corpus_from_M1_M2(type_only, n_tokens)
    m1 = corpus_summary(m1_words, "M1 pos*len (type-fit)")

    print("M2 (position × length, token-weighted fit)...")
    m2_words = sample_corpus_from_M1_M2(real_words, n_tokens)
    m2 = corpus_summary(m2_words, "M2 pos*len (token-fit)")

    print("M3 (family + position × length)...")
    m3_words = sample_corpus_from_M3(real_words, n_tokens)
    m3 = corpus_summary(m3_words, "M3 family + pos*len")

    results = [real, m1, m2, m3]
    keys = ["label", "n_tokens", "n_types", "hapax_ratio", "avg_word_length",
            "h1_unigram", "h2_conditional", "zipf_slope", "zipf_r2",
            "repetition_rate", "graph_n_types_used", "graph_avg_degree",
            "graph_largest_share", "graph_clustering", "graph_components_geq_10"]

    print("\n=== COMPARISON ===")
    print(f"{'metric':<26} | " + " | ".join(f"{r['label'][:18]:>18}" for r in results))
    print("-" * 120)
    for k in keys[1:]:
        vals = [r[k] for r in results]
        fmt = lambda v: f"{v:>18.4f}" if isinstance(v, float) else f"{v:>18}"
        print(f"{k:<26} | " + " | ".join(fmt(v) for v in vals))

    out = {"results": results}
    (ROOT / "generative_results.json").write_text(
        json.dumps(out, indent=2, ensure_ascii=False), encoding="utf-8")
    csv_lines = [",".join(keys)]
    for r in results:
        csv_lines.append(",".join(str(r[k]) for k in keys))
    (ROOT / "generative_summary.csv").write_text("\n".join(csv_lines) + "\n", encoding="utf-8")
    print(f"\nWrote {ROOT/'generative_results.json'} and {ROOT/'generative_summary.csv'}")


if __name__ == "__main__":
    main()
